config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'posts#index'
  resources :posts do
    collection do
      get 'search'
    end
    resources :comments, only: :create
  end
  resources :users, only: :show
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, presence: true
  validates :post, presence: true
  validates :user, presence: true


  belongs_to :user
  belongs_to :post
end

app/models/place.rb
class Place < ActiveHash::Base
  self.data = [
    { id: 1, name: '屋内' },
    { id: 2, name: '屋外' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
  validates :detail, presence: true
  validates :size_id, presence: true
  validates :place_id, presence: true
  validates :image, presence: true


  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :size
  belongs_to :place
end

app/models/size.rb
class Size < ActiveHash::Base
  self.data = [
    { id: 1, name: '2mm以下' },
    { id: 2, name: '3mm~1cm' },
    { id: 3, name: '1cm以上' }
  ]

  include ActiveHash::Associations
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true

  has_many :posts
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :basic_auth
  

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"] 
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(post_params)
    if @comment.save
      redirect_to post_path(@comment.post)
    else
      @post = @comment.post
      @comments = @post.comments.includes(:user)
      render "posts/show"
    end
  end

  private
  def post_params
    params.require(:comment).permit(:content).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]

  def index
    @post = Post.includes(:user).order("created_at DESC")
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to "/"
    else
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
  end
  
  def edit
    @post = Post.find(params[:id])
    unless @post.user.id == current_user.id
      redirect_to action: :index
    end
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    if @post.update(post_params)
      redirect_to post_path(@post.id)
    else 
      render :edit
    end
  end

  def search
    @q = Post.ransack(params[:q])
    @posts = @q.result
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to "/"
  end


  private
  def post_params
    params.require(:post).permit(:detail, :size_id, :place_id, :image).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>GaichuBusters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <nav class="navbar fixed-top navbar-light bg-white">
        <div class="container-fluid"> 
          <%= link_to image_tag("logo.jpg", class:"navbar-brand"), "/" %>
          
          
       


          <% if user_signed_in? %>
            <div class="nav__right"> 
              <%= link_to '検索', search_posts_path, :class => "btn btn-outline-secondary btn-sm"%>
              <%= link_to "ログアウト", destroy_user_session_path,method: :delete, :class =>"btn btn-outline-danger btn-sm"%>
              <%= link_to "新規投稿", new_post_path, :class =>"btn btn-outline-success btn-sm" %>
            </div> 
          <% else  %>
            <div class="nav__right">
              <%= link_to '検索', search_posts_path, :class => "btn btn-outline-secondary btn-sm"%>
              <%= link_to "ログイン", user_session_path, :class =>"btn btn-outline-warning btn-sm" %>
              <%= link_to "新規登録", new_user_registration_path, :class =>"btn btn-outline-primary btn-sm" %>
            </div>
          <% end %>
        </div>
      </nav>
    </header>

  



    <%= yield %>


    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |f|%>


  <div class="form-group">
    <%= f.label :size_id, "害虫の大きさ" %><br />
    <%= f.collection_select(:size_id, Size.all, :id, :name, {}, {class:"select-box", id:"size"}) %>
  </div>
 

 
  <div class="form-group">
    <%= f.label :detail, "害虫の出現場所" %><br />
    <%= f.collection_select(:place_id, Place.all, :id, :name, {}, {class:"select-box", id:"place"}) %>
  </div>


  <div class="form-group">
    <%= f.label :detail, "害虫の特徴"%><br />
    <%= f.text_area :detail, id:"post_title", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image, "害虫の画像" %><br />
    <%= f.file_field :image, id:"post_image" %>
  </div>

  <div class="actions">
    <%= f.submit "対処法を聞く", :class => "btn btn-primary"  %>
  </div>

<% end %>

app/views/posts/_post.html.erb
<div class="filter"> 
  <div class="album py-3 ">
    <div class="container">
      <div class="card__body">
        <%= link_to image_tag( post.image.variant(resize: '300x300'), :class => "img-fluid"), post_path(post.id)%>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="inner">
  <div class="card col-sm-5 mx-auto mt-5">
    <div class="card-body">
      <div class="form-group">
        <h2 class="mt-1 mb-3">投稿編集</h2>
        <%= render partial: "form" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<main class="main">
  <div class="inner">
    <% if user_signed_in? %>
      <div class="greeting">
        <%= 'こんにちは、' %>
        <%= link_to current_user.name, user_path(current_user.id), class: :greeting__link%>
        <%= 'さん' %>
      </div>
    <% end %>

    

    <div class="background">
      <section class="py-3 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
              <h1 class="fw-bold">==CAUTION!==</h1>
              <p class="lead-text">詳細では鮮明な画像が表示されます</p>
            </div>
        </div>
      </section>
    </div>
   
    

    <div class="card__wrapper">
      <%= render partial: "post", collection: @post %>
    </div>
  </div>
</main>

app/views/posts/new.html.erb
<div class="inner">
  <div class="card col-sm-5 mx-auto mt-5">
    <div class="card-body">
      <div class="form-group">
        <h2 class="mt-1 mb-3">新規投稿</h2>
          <%= render partial: "form" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<main class="main">
  <div class="inner">
      <div class="card col-sm-5 mx-auto mt-5">
        <div class="card-body">
          <div class="search-contents">
            <h2 class="mt-1 mb-3">検索</h2>
            <%= search_form_for @q, url: search_posts_path, html: {id: "detailed-search-form"} do |f| %>
              <div class="form-group">
                <%= f.label :size_id_eq, '害虫の大きさ' %>
                <br>
                <%= f.collection_select(:size_id_eq, Size.all, :id, :name, {include_blank: "---"}) %>
              </div>

              <div class="form-group">
                <%= f.label :place_id_eq, '害虫の出現場所' %>
                <br>
                <%= f.collection_select(:place_id_eq, Place.all, :id, :name, {include_blank: "---"}) %>
              </div>

              <div class="form-group">
                <%= f.label :detail_cont, '害虫の特徴' %>
                <br>
                <%= f.text_field :detail_cont %>
             </div>

              <%= f.submit '検索' %>
            <% end %>
          </div>
        </div>
      </div>

    <div class="card__wrapper">
        <% @posts.each do |post| %>
        <div class="filter"> 
          <div class="album py-3 ">
            <div class="container">
              <div class="card__body">
                <%= link_to image_tag( post.image.variant(resize: '300x300'), :class => "img-fluid"), post_path(post.id)%>
              </div>
            </div>
          </div>
        </div>
        <% end %>
    </div>
  </div>
</main>

app/views/posts/show.html.erb
<div class="inner">
  <main class="card col-sm-5 mx-auto mt-5">
    <div class="card-body">
      <div class="post__wrapper">
        <%= link_to @post.user.name, user_path(@post.user.id), class: :post__user %>
        <% if user_signed_in? && current_user.id == @post.user.id %>
          <div class="d-grid gap-2 d-md-flex justify-content-md-end">
            <%= link_to "編集する", edit_post_path(@post.id), :class => "btn btn-primary", method: :get %>
            <%= link_to "削除する", post_path(@post.id), :class => "btn btn-danger", method: :delete %>
          </div>
        <% end %>
        <div class="card-body">
          <%= image_tag @post.image, :class => "img-fluid" %>
        </div>
        <div class="card-body">
        <div class="post__body">
          <div class="post__detail">
            <p class="detail__title">害虫の特徴</p>
            <p class="size__detail">サイズ: 
              <%= @post.size.name %>
            </p>
            <p class="place__detail">出現場所: 
              <%= @post.place.name %>
            </p>
            <p class="detail__message">
              <%= @post.detail %>
            </p>
          </div>
        </div>
        <div class="post__comments">
          <% if user_signed_in? %>
            <%= form_with model: [@post, @comment],local: true do |f|%>
              <div class="form-group">
                <%= f.label :comment, "回答文" %><br />
                <%= f.text_area :content, id:"comment_content", :class => "form-control" %>
              </div>
              <div class="actions">
                <%= f.submit "回答する", :class => "btn btn-outline-success" %>
              </div>
            <% end %>
          <% end %>
          <ul class="comments_lists">
          <p class="detail__title">--- 回答 ---</p>
            <% @comments.each do |comment| %>
              <li class="comments_list">
                <%= comment.content %>
                <%= link_to comment.user.name , user_path(comment.user.id), class: :comment_user %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main class="main">
  <div class="inner">
    <div class="background">
      <section class="py-3 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
              <h1 class="fw-bold">==CAUTION!==</h1>
              <p class="lead-text">詳細では鮮明な画像が表示されます</p>
            </div>
        </div>
      </section>
    </div>

    <h2 class="form-group">
      <span>・<%= @user.name %>さんの投稿</span>
    </h2>
    <div class="card__wrapper">
      <%= render partial: "posts/post", collection: @user.posts %>
    </div>
  </div>
</div>